package by.psrer.entity.enums;

public enum UserState {
    BASIC,
    AREA_SELECTION,
    DEPARTMENT_SELECTION,
    FIO_SELECTION,
    ADD_ADMIN_SELECTION,
    REMOVE_ADMIN_SELECTION,
    GRANT_ACCESS_SELECTION,
    REVOKE_ACCESS_SELECTION
}