package by.psrer.entity.enums;

public enum UserState {
    BASIC,
    AREA_SELECTION,
    DEPARTMENT_SELECTION,
    FIO_SELECTION,
    ADD_ADMIN_SELECTION,
    REMOVE_ADMIN_SELECTION,
    GRANT_ACCESS_SELECTION,
    REVOKE_ACCESS_SELECTION,
    ADD_AREA_SELECTION,
    REMOVE_AREA_SELECTION,
    ADD_DEPARTMENT_SELECTION_AREA,
    ADD_DEPARTMENT_SELECTION_DEPARTMENT,
    REMOVE_DEPARTMENT_SELECTION,
    ADD_JOB_SELECTION,
    REMOVE_JOB_SELECTION
}